project_id = "jrebsrdxgvkdiirhvthv"

[functions.ai-extract]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.ai-reminders]
verify_jwt = false

[functions.ai-connections]
verify_jwt = false

[functions.ai-merge]
verify_jwt = false

[functions.ai-tag-contacts]
verify_jwt = false
